{% set name = "vegafusion" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vegafusion-{{ version }}.tar.gz
  sha256: cf3032998ffd2ee281f030842d5e3edf45d23eea90909529e9715789595101fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm >=2.0.0, <3
  run:
    - altair >=4.2.0
    - pandas
    - psutil
    - pyarrow >=6
    - python >=3.7
    - vegafusion-python-embed

test:
  imports:
    - vegafusion
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/vegafusion/
  summary: Core tools for using VegaFusion from Python
  license: AGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jonmmease
