{% set name = "vegafusion" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vegafusion-{{ version }}.tar.gz
  sha256: 8526051fd8f016736d585692fbf964ad1b397ade32a15cf889b67a2be1030804

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm >=2.0.0, <3
  run:
    - altair >=4.2.0
    - pandas
    - psutil
    - pyarrow >=6
    - python >=3.7
    - vegafusion-python-embed >=1.0

test:
  imports:
    - vegafusion
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://vegafusion.io
  summary: Core tools for using VegaFusion from Python
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jonmmease
