{% set name = "vegafusion" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vegafusion-{{ version }}.tar.gz
  sha256: ef9430245569e45d0c00e4bb0023e5b290e6060ce2b567a5f2fe3e4f807a164b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - setuptools_scm
  run:
    - altair >=4.2.0
    - pandas
    - psutil
    - pyarrow >=6
    - python >=3.7
    - vegafusion-python-embed

test:
  imports:
    - vegafusion
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/vegafusion/
  summary: Core tools for using VegaFusion from Python
  license: AGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jonmmease
