{% set name = "vegafusion" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vegafusion-{{ version }}.tar.gz
  sha256: 6e3e087608bc80975affdc38072ee7139b8afd1620422cbf16c4f5f067d6d459

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - altair >=4.2.0
    - pandas
    - psutil
    - pyarrow >=6
    - python >=3.7
    - vegafusion-python-embed

test:
  imports:
    - vegafusion
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/vegafusion/
  summary: Core tools for using VegaFusion from Python
  license: AGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jonmmease
