{% set name = "vegafusion" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vegafusion-{{ version }}.tar.gz
  sha256: 5747d306ded35f569cde67a1aec9df73aebf41713b716dd6eb4e6504295cc49c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm >=2.0.0, <3
  run:
    - altair >=4.2.0
    - pandas
    - psutil
    - pyarrow >=6
    - python >=3.7
    - vegafusion-python-embed

test:
  imports:
    - vegafusion
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/vegafusion/
  summary: Core tools for using VegaFusion from Python
  license: AGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jonmmease
